{{- include "ffc-helm-library.deployment" (list . "ffc-sfi-pocs.deployment") -}}
{{- define "ffc-sfi-pocs.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-sfi-pocs.container") }}
{{- end -}}
