apiVersion: v2
description: Microservice for SFI POC work
name: ffc-sfi-pocs
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
