environment: development
name: ffc-sfi-pocs
namespace: ffc-sfi
workstream: ffc-sfi
image: ffc-sfi-pocs

labels: {}

containerConfigMap:
  name: ffc-sfi-pocs-config-map

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

ingress:
  class: nginx
  endpoint: ffc-sfi-pocs
  server: replaced.by.config.com
